name: TestPlugin
version: '${project.version}'
main: its.wurm.testplugin.Main
api-version: 1.17
authors: [ Wurm ]
description: learning how to do plugin stuff
commands:
  giveall:
    description: Give all test items to the player
    usage: /<command>
  testgui:
    description: Open a custom GUI to the player
    usage: /<command>
  customsummon/dummy:
    description: Summon the Dummy mob
    usage: /<command>
  marker:
    description: Create a damage marker
    usage: /<command>
  summonall:
    description: Create a Custom Mob
    usage: /<command>
  summonnew:
    description: Create a Custom Mob
    usage: /<command>
  check:
    description: check player's item
    usage: /<command>