name: TestPlugin
version: '${project.version}'
main: its.wurm.testplugin.Main
api-version: 1.17
authors: [ Wurm ]
description: learning how to do plugin stuff
commands:
  giveall:
    description: Give all test items to the player
    usage: /<command>
  testgui:
    description: Open a custom GUI to the player
    usage: /<command>
  customsummon/dummy:
    description: Summon the Dummy mob
    usage: /<command>
  summonzombie:
    description: Summon every zombie variant
    usage: /<command>
  customsummon/smolGhast:
    description: Summon a Baby Ghast
    usage: /<command>
  marker:
    description: Create a damage marker
    usage: /<command>
  customsummon/noviceSkele:
    description: Create a Novice Skeleton
    usage: /<command>
  check:
    description: check player's item
    usage: /<command>